[#33] Develop site front page
Sheptytskyid/Startup_Platform pull request #20
Opened 2017-04-28 12:11 UTC by GetFire

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a href="#"><i class="fa fa-facebook"></i></a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a class="navbar-brand" href="#">Great<i class="fa fa-rocket fa-lg" aria-hidden="true"></i>Start </a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a href="#"><i class="fa fa-vk"></i></a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +<head>
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add a 'favicon' declaration in this 'header' tag. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3APageWithoutFaviconCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="fa fa-lightbulb-o fa-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <p><b>Just Text Example</b><br>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <b> tag by <strong>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="glyphicon glyphicon glyphicon-grain gi-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                        <i class="fa fa-close"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <p><b>Just Text Example</b><br>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <b> tag by <strong>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                <!--<li class="active"><a  class="btn btn-success btn-md" href="#modal-login" data-toggle="modal" >Login</a></li>-->
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove this commented out code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AAvoidCommentedOutCodeCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="fa fa-users fa-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <p><b>Just Text Example</b><br>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <b> tag by <strong>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a href="#"><i class="fa fa-twitter"></i></a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <i class="fa fa-user-circle-o"></i> Create an account
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 05:17 UTC, Sheptytskyid commented
SonarQube analysis reported 22 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 20 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-29 14:30 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-04-30 06:43 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-01 13:04 UTC, zozich requested changes
Good, but there are mistakes that should be corrected

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +<head>
Do this

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                <!--<li class="active"><a  class="btn btn-success btn-md" href="#modal-login" data-toggle="modal" >Login</a></li>-->
Do this

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +<div class="container w">
Do you consider `w` to be a meaningful class name?

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <p><b>Just Text Example</b><br>
Here SonarQube is right. NEVER apply bold font by using tag <b>. This type of usage is already deprecated for a long time. You should do it via CSS, or use other tags as advised by SonarQube

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
It is also not advised to use <br> tags. You may achieve the same effect using only CSS. This will be more semantic

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a class="navbar-brand" href="#">Great<i class="fa fa-rocket fa-lg" aria-hidden="true"></i>Start </a>
These ones that relate to icons in the <i> tag may be ignored

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/resources/css/main.css
> +    /*background-position: center center;*/
Why do you have commented code here?

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/resources/css/main.css
> +    /*background-size: 100%;*/
Why do you have commented code here?

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/resources/css/main.css
> +#headerwrap h1 {
It is not advised to use ids and CSS selectors. All CSS styles should better be assigned using classes. Correct here, and all the other instances as well

2017-05-01 13:04 UTC, zozich commented on src/main/webapp/resources/css/main.css
> +.w {
?

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented
SonarQube analysis reported 21 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 20 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 07:32 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:03 UTC, Sheptytskyid commented
SonarQube analysis reported 20 issues
* ![MINOR][MINOR] 20 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 08:24 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a class="navbar-brand" href="#">Great<i class="fa fa-rocket fa-lg" aria-hidden="true"><text/></i>Start </a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 10:26 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="fa fa-lightbulb-o fa-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>min<br><i class="fa fa-dollar"></i>100000 <br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <p>Still needed</br><i class="fa fa-dollar"></i>9999<br></p>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a href="#"><i class="fa fa-twitter"></i></a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a class="navbar-brand" href="#">Great<i class="fa fa-rocket fa-lg" aria-hidden="true">
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 12:35 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <a href="#"><i class="fa fa-facebook"></i></a>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:02 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:14 UTC, zozich approved these changes
Much better now

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="glyphicon glyphicon glyphicon-grain gi-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +            <i class="fa fa-users fa-3x"></i>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div><i class="fa fa-dollar"></i>100000</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/DesignPage.html
> +                            <div class="right-box"><i class="fa fa-dollar"></i>9999</div>
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Replace this <i> tag by <em>. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3ABoldAndItalicTagsCheck)

2017-05-02 13:41 UTC, Sheptytskyid commented
SonarQube analysis reported 17 issues
* ![MINOR][MINOR] 17 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-02 13:43 UTC, merged