[#19] Develop investment interest contents (cards) (Front-end + entity + table in DB + mapping)
Sheptytskyid/Startup_Platform pull request #24
Opened 2017-04-29 14:37 UTC by Potyomkin-Igor

[#19] Develop investment interest contents (unchecked version)

2017-04-30 20:54 UTC, GetFire commented
• При переходе на страничку /inv_interests кидает ексепшен **org.postgresql.util.PSQLException: ERROR: column investment0_.goal does not exist**
• Есть конфликты с мастером
•Странно, не знаю почему, скачал твою ветку, у меня в контроллере есть маппинг типа  **@RequestMapping("/inv_interests")**. В гите маппинг без нижнего подчеркивания. Поправь в коде

2017-05-01 06:36 UTC, Potyomkin-Igor commented
Очень странно, уже нет такого перехода  /inv_interests. Скорее всего это из-за того, что мастер обновили после того как я создал бранчу.

2017-05-02 06:20 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentInterestController.java
> +        // TODO: get authenticated user once user authorization is ready
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1135)

2017-05-02 06:20 UTC, Sheptytskyid commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'

2017-05-02 10:14 UTC, GetFire commented
В принципе все работает, но:
• Файл .sonar/.sonar_lock необходим тут? 
• При редактировании и создании нового интереса нет проверки поля **Amount of Investment** При вводе туда текста, падает ексепшен

2017-05-02 14:01 UTC, Potyomkin-Igor commented
Что то я не пойму за файл .sonar/.sonar_lock где он лежит этот файл

2017-05-04 07:25 UTC, zozich requested changes
Please amend

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/controllers/InvestmentInterestController.java
> +    @RequestMapping("/invinterest")
Move root mapping common to all methods to controller level

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/controllers/InvestmentInterestController.java
> +    @RequestMapping(value = "/invinterest/add", method = RequestMethod.POST)
Change mapping according to REST infrastructure

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/controllers/InvestmentInterestController.java
> +        this.investmentInterestService.createInvestmentInterest(investmentInterest);
Why do you use `this`? It is not needed here

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/dao/hibernate/InvestmentInterestDaoImpl.java
> +
? why empty space?

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/dao/hibernate/InvestmentInterestDaoImpl.java
> +    @Override
Try moving all these methods to generic DAO impl. Currently they are all the same for all entities

2017-05-04 07:25 UTC, zozich commented on src/main/java/net/greatstart/services/InvestmentInterestService.java
> +        return this.investmentInterestDao.create(investmentInterest);
`this` is not needed in this context

2017-05-04 10:21 UTC, Potyomkin-Igor commented on src/main/java/net/greatstart/dao/hibernate/InvestmentInterestDaoImpl.java
> +    @Override
The next our step will be crossing to Spring DATA(CrudRepository or JpaRepository), why to do that?

2017-05-04 16:23 UTC, zozich approved these changes
👍

2017-05-04 17:18 UTC, merged