Readme.md
Sheptytskyid/Startup_Platform pull request #30
Opened 2017-05-03 12:34 UTC by semyonov-m-y

2017-05-03 16:22 UTC, GetFire reviewed
Можно еще добавить Spring framework, CSS, HTML и другие технологии, в список используемых технологий

2017-05-04 06:42 UTC, holkwen commented
А Spring и Hibernate нигде не упоминаем? :)

2017-05-04 07:16 UTC, zozich requested changes
Take a look

2017-05-04 07:16 UTC, zozich commented on README.md
> +* **Serialization**
Really? :)

2017-05-04 07:16 UTC, zozich commented on README.md
> +* **Power Mockito**
Are you sure?)

2017-05-04 09:10 UTC, zozich approved these changes

2017-05-04 17:15 UTC, merged