#40 implement crud of investments (back end)
Sheptytskyid/Startup_Platform pull request #36
Opened 2017-05-06 09:59 UTC by AlexPoliteRudenko

2017-05-16 16:14 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +    //todo
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1135)

2017-05-16 16:14 UTC, Sheptytskyid commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-05-16 17:01 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        investmentService.deleteInvestment(id);
what if ID is invalid?

2017-05-16 17:06 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +    private static final String WRONG_MIN_VALUE = "You entered wrong investment value. "
store these in .properties file and retrieve via MessageSource

2017-05-16 17:07 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +    public static String validate(BigDecimal sum, Project project) {
Why static?

2017-05-16 17:08 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +@Component
component with private constructor?

2017-05-16 17:08 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +
remove double line breaks

2017-05-16 17:09 UTC, Sheptytskyid commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/startup_platform
this will work only for you

2017-05-16 17:10 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/investment/add_investment.jsp
> +    <p>Here you can add you investment in ${project.desc.name}</p>
Here you can add youR investment

2017-05-16 17:10 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/investment/investments.jsp
> +								<a href="project/${investment.project.id}">${investment.project.desc.name}</a>
check indentation (4 spaces)

2017-05-16 21:03 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return new ModelAndView(REDIRECT + PROJECT_PAGE + id);
Create empty model (ModelAndView). Fill it depending on condition and return at the end instead of returning 3 different models.

2017-05-16 21:04 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return investmentService.getInvestmentById(id);
no ModelAndView?

2017-05-16 21:04 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +            model.addObject("message", "Please enter your phone number!");
Use MessageSource instead of hardcoding messages

2017-05-16 21:06 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return projectService.getProjectById(id).getInvestments();
no Model?

2017-05-16 21:08 UTC, Sheptytskyid commented on src/main/java/net/greatstart/model/User.java
> +    @OneToMany(mappedBy = "investor", fetch = FetchType.LAZY)
this caused me problems when getting User from DB in Forgot Password branch. Please, leave EAGER here and afterwards

2017-05-16 21:10 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +    public static String validate(BigDecimal sum, Project project) {
Why static?

2017-05-16 21:10 UTC, Sheptytskyid commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +@Component
Component with private constructor?

2017-05-16 21:11 UTC, Sheptytskyid commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/startup_platform
why did you change this?

2017-05-16 21:12 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/investment/add_investment.jsp
> +				<button type="button" class="close" data-dismiss="alert">
check indentation (4 spaces)

2017-05-16 21:13 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/investment/add_investment.jsp
> +		<p>Here you can add you investment in ${project.desc.name}</p>
Here you can add youR investment

2017-05-16 21:13 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/investment/investments.jsp
> +								<a href="project/${investment.project.id}">${investment.project.desc.name}</a>
indentation

2017-05-16 21:43 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return investmentService.getInvestmentById(id);
fix

2017-05-16 21:43 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return projectService.getProjectById(id).getInvestments();
fix

2017-05-16 21:52 UTC, AlexPoliteRudenko commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/startup_platform
ups. Sorry. Its my bad. I have problems using default db

2017-05-16 21:55 UTC, AlexPoliteRudenko commented on src/main/webapp/WEB-INF/views/investment/add_investment.jsp
> +		<p>Here you can add you investment in ${project.desc.name}</p>
fixed

2017-05-16 21:55 UTC, AlexPoliteRudenko commented on src/main/webapp/WEB-INF/views/investment/investments.jsp
> +								<a href="project/${investment.project.id}">${investment.project.desc.name}</a>
fixed

2017-05-16 21:59 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        return new ModelAndView(REDIRECT + PROJECT_PAGE + id);
done

2017-05-16 22:03 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +@Component
yes. I copied structure of this validation service from UserValidationService and unfortunately cannot answer your question with details.

2017-05-16 22:03 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +    public static String validate(BigDecimal sum, Project project) {
I copied structure of this validation service from UserValidationService and unfortunately cannot answer your question with details. ((

2017-05-17 09:26 UTC, GetFire commented
Исправь баги с ссылками и окном логина, в хедере(хотя наверно это уже не так актуально)

2017-05-17 15:29 UTC, holkwen commented
@GetMapping("/project/{id}/addInvestment")
Использование верхнего регистра в URL считается плохой практикой.

Надо, чтобы coveralls тоже проходило.

У меня при добавлении инвестиции выдает ошибку:
There was an unexpected error (type=Internal Server Error, status=500).
Neither BindingResult nor plain target object for bean name 'dtoUserProfile' available as request attribute

2017-05-17 15:34 UTC, holkwen commented
model.addObject(principal);
А зачем добавлять principal во вьюшку? Лучше бы DtoUserProfile добавить :)

2017-05-17 15:49 UTC, AlexPoliteRudenko commented
Прибрав валідацію на наявність телефонного номеру у юзера. Тести найближчим часом додам

2017-05-17 16:02 UTC, holkwen commented
Насколько я понимаю, post всё равно идет на addInvestment? Теперь ошибка из-за того, что такого маппинга нет :)

2017-05-18 23:58 UTC, AlexPoliteRudenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [[#56] Implement CRUD of investments (back-end)](https://trello.com/c/eKDaQwhs/39-56-implement-crud-of-investments-back-end)

2017-05-19 12:24 UTC, zozich requested changes
Amend

2017-05-19 12:24 UTC, zozich commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        model.addObject(PAGE_NAME, "Investments of user: "
Why not use String.format for that?

2017-05-19 12:24 UTC, zozich commented on src/main/java/net/greatstart/model/Investment.java
> +    LocalDateTime dateOfInvestment;
Why did you remove private? If it was done for tests, it is unacceptable solution

2017-05-19 12:24 UTC, zozich commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +        if (sum.divideAndRemainder(minInvestment)[1]
One line is enough here, you shouldn't break it

2017-05-19 12:24 UTC, zozich commented on src/main/webapp/WEB-INF/views/investment/investments.jsp
> +							<h4>Project name:
You should have 4 spaces index at max. This is not readable. You have 4 tabs here

2017-05-19 12:24 UTC, zozich commented on src/test/java/net/greatstart/controllers/InvestmentControllerTest.java
> +    public void addCorrectInvestment() throws Exception {
Make all test names human readable

2017-05-19 12:24 UTC, zozich commented on src/test/java/net/greatstart/controllers/InvestmentControllerTest.java
> +        User user = new User();
You made this at least in 2 tests. Why not move this user to an instance variable and then just use it in several tests?

2017-05-19 12:24 UTC, zozich commented on src/test/java/net/greatstart/services/InvestmentServiceTest.java
> +    @Test(timeout = 2000)
Why do you have timeout here? It is not needed on service level

2017-05-19 18:53 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/model/Investment.java
> +    LocalDateTime dateOfInvestment;
Because i found interesting Annotation in Lombok:

2017-05-19 18:56 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/validators/InvestmentValidationService.java
> +        if (sum.divideAndRemainder(minInvestment)[1]
Fixed

2017-05-19 19:20 UTC, AlexPoliteRudenko commented on src/test/java/net/greatstart/controllers/InvestmentControllerTest.java
> +    public void addCorrectInvestment() throws Exception {
Done

2017-05-19 19:22 UTC, AlexPoliteRudenko commented on src/test/java/net/greatstart/controllers/InvestmentControllerTest.java
> +        User user = new User();
Thnx. Done

2017-05-19 19:23 UTC, AlexPoliteRudenko commented on src/test/java/net/greatstart/services/InvestmentServiceTest.java
> +    @Test(timeout = 2000)
Remove from every service tests? I made it on purpose.

2017-05-19 19:34 UTC, AlexPoliteRudenko commented on src/main/java/net/greatstart/controllers/InvestmentController.java
> +        model.addObject(PAGE_NAME, "Investments of user: "
Done. Thnx - great solution! )))

2017-05-19 19:35 UTC, AlexPoliteRudenko commented on src/main/webapp/WEB-INF/views/investment/investments.jsp
> +							<h4>Project name:
It's really strange. In Idea all looks good. 
![image](https://cloud.githubusercontent.com/assets/19539879/26263944/79a5aa64-3ce3-11e7-9cc4-9d4a9dc3594f.png)

2017-05-19 19:37 UTC, AlexPoliteRudenko commented on src/test/java/net/greatstart/services/InvestmentServiceTest.java
> +    @Test(timeout = 2000)
Done

2017-05-19 22:21 UTC, zozich approved these changes
OK

2017-05-20 00:15 UTC, merged