[#53] Develop "add/edit entity" template + pages(first commit for che…
Sheptytskyid/Startup_Platform pull request #41
Opened 2017-05-08 15:05 UTC by Potyomkin-Igor

[#53] Develop "add/edit entity" template + pages(first commit for check in)

2017-05-13 16:19 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/addPages/add_investment.html
> +                                <p align="center">Here you can add you investment in <u>Project</u></p>
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this deprecated "align" attribute. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AS1827)

2017-05-13 16:19 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/addPages/add_investment.html
> +                                <p align="center">Total investment needed: <u>100000</u>
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this deprecated "align" attribute. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AS1827)

2017-05-13 16:19 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/addPages/add_investment.html
> +                                <p align="center">Minimal investment: <u>5000</u>
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this deprecated "align" attribute. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AS1827)

2017-05-13 16:19 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/addPages/add_invinterest.html
> +                                    <!--<input id="cost" name="cost" type="number" style="width: 300px "  placeholder="Cost"-->
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AAvoidCommentedOutCodeCheck)

2017-05-13 16:19 UTC, Sheptytskyid commented on src/main/webapp/WEB-INF/views/editPages/edit_invinterest.html
> +                                    <!--<input id="cost" name="cost" type="number" style="width: 300px "  placeholder="Cost"-->
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this commented out code. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=Web%3AAvoidCommentedOutCodeCheck)

2017-05-13 16:19 UTC, Sheptytskyid commented
SonarQube analysis reported 5 issues
* ![MAJOR][MAJOR] 5 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-14 08:59 UTC, Sheptytskyid commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 2 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-15 19:28 UTC, GetFire commented
Я бы все таки переделал их под модальные окна. Но так тоже нормально. Не забудь обновить ветку

2017-05-16 06:10 UTC, semyonov-m-y commented
Всё вроде бы ок. Вот только почему ДВА раза отображается add_invinterest.html в файлах? - 160 и 139 строк в них

2017-05-16 08:51 UTC, zozich requested changes
Amend everywhere

2017-05-16 08:51 UTC, zozich commented on src/main/webapp/WEB-INF/views/addPages/add_event.html
> +                        <div class="col-xs-12">
What's the point? 12 is default value

2017-05-16 08:51 UTC, zozich commented on src/main/webapp/WEB-INF/views/addPages/add_event.html
> +                                <div class="col-xs-12 col-md-6 col-lg-8" style="margin-bottom: 25px">
Is it intentional that on larger screens it is larger than on medium ones?

2017-05-16 08:51 UTC, zozich commented on src/main/webapp/WEB-INF/views/addPages/add_event.html
> +<div class="modal fade" id="modal-login">
Why d you have modal login inline? You should have one template for all pages

2017-05-16 08:51 UTC, zozich commented on src/main/webapp/WEB-INF/views/addPages/add_event.html
> +<script src="js/salvattore.min.js"></script>
Do you really need it?

2017-05-16 08:51 UTC, zozich commented on src/main/webapp/WEB-INF/views/addPages/add_investment.html
> +<div class="modal fade" id="modal-login">
What is login form doing here?

2017-05-16 12:56 UTC, Potyomkin-Igor commented on src/main/webapp/WEB-INF/views/addPages/add_event.html
> +                        <div class="col-xs-12">
but, if I explicitly specify this parameter, the form as it becomes more collected

2017-05-16 14:12 UTC, zozich approved these changes
OK

2017-05-16 18:24 UTC, merged