[#41] Migrate to Spring Data
Sheptytskyid/Startup_Platform pull request #42
Opened 2017-05-08 19:43 UTC by Sheptytskyid

2017-05-08 19:46 UTC, Sheptytskyid commented on src/main/java/net/greatstart/configs/SecurityConfig.java
> +    private DataSource dataSource;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this unused "dataSource" private field. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1068)

2017-05-08 19:46 UTC, Sheptytskyid commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2017-05-09 14:35 UTC, holkwen commented
У меня новые проекты перестали добавляться.

2017-05-09 14:52 UTC, holkwen commented
Лечится добавлением в pom.xml:
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-java8</artifactId>
            <version>${hibernate.version}</version>
        </dependency>

2017-05-10 15:55 UTC, zozich requested changes
Please amend

2017-05-10 15:55 UTC, zozich commented on pom.xml
> +                <configuration>
This is not needed. Your `model` and `dto` classes should be tested withing testing other layers

2017-05-10 15:55 UTC, zozich commented on pom.xml
> +            <groupId>org.powermock</groupId>
Remove if not needed

2017-05-10 15:55 UTC, zozich commented on src/main/java/net/greatstart/dao/ProjectDao.java
> +    List<Project> findAll(Pageable numberOfRecords);
Don't you have it by default?

2017-05-10 15:55 UTC, zozich commented on src/main/java/net/greatstart/dto/DtoUser.java
> +@Component
Why?

2017-05-10 15:55 UTC, zozich commented on src/main/java/net/greatstart/dto/DtoUserProfile.java
> +@Component
Why? Remove everywhere

2017-05-10 15:55 UTC, zozich commented on src/main/java/net/greatstart/controllers/EventController.java
> +        eventService.saveEvent(event);
save should return saved entity as done by default by Spring Data

2017-05-11 09:32 UTC, zozich approved these changes
Okay now

2017-05-11 11:18 UTC, merged