Completly migrate UserPage and EditUserPage to angularjs
Sheptytskyid/Startup_Platform pull request #57
Opened 2017-05-22 13:29 UTC by GetFire

2017-05-24 15:18 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +            return new ResponseEntity<DtoUserProfile>(dtoUser, HttpStatus.OK);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2293)

2017-05-24 15:18 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +        return new ResponseEntity<DtoUserProfile>(currentDtoUser, HttpStatus.OK);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2293)

2017-05-24 15:18 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +        return new ResponseEntity<DtoUserProfile>(HttpStatus.NOT_FOUND);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2293)

2017-05-24 15:18 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +            return new ResponseEntity<DtoUserProfile>(dtoUser, HttpStatus.OK);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2293)

2017-05-24 15:19 UTC, Sheptytskyid commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +        return new ResponseEntity<DtoUserProfile>(HttpStatus.NOT_FOUND);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS2293)

2017-05-24 15:19 UTC, Sheptytskyid commented on src/main/java/net/greatstart/services/UserService.java
> +        System.out.println("return user by id " + id);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS106)

2017-05-24 15:19 UTC, Sheptytskyid commented on src/main/java/net/greatstart/services/UserService.java
> +        System.out.println("find by email " + email);
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS106)

2017-05-24 15:19 UTC, Sheptytskyid commented
SonarQube analysis reported 7 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 5 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-24 19:40 UTC, zozich requested changes
Please amend

2017-05-24 19:40 UTC, zozich commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +public class UserRestController {
Word Rest is not needed in controller name. All your controller will be rest ones

2017-05-24 19:40 UTC, zozich commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +        User user = userService.getUserByEmail(principal.getName());
All logic should be moved to a service level

2017-05-24 19:40 UTC, zozich commented on src/main/resources/static/app/service/LoginService.js
> +    .factory('loginService', function ($rootScope, $http) {
Name of factories usually starts from uppercase letter - the same as for Java classes

2017-05-24 19:40 UTC, zozich commented on src/main/resources/static/views/user/UserController.js
> +        $scope.user = angular.copy($rootScope.currentUser);
Add toDo comment to rework this to a more direct logic. Looks like a hotfix

2017-05-24 19:40 UTC, zozich commented on src/main/resources/static/views/user/UserController.js
> +                $location.path('/user/:id', $scope.user.id);
You are changing location irrespective of whether you request to server was successful

2017-05-24 19:40 UTC, zozich commented on src/test/java/net/greatstart/controllers/UserRestControllerTest.java
> +        user = new User();
You don't need @Before section to do this, you can do this inline above where you declare a variable

2017-05-25 07:53 UTC, GetFire commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +public class UserRestController {
fix

2017-05-25 07:53 UTC, GetFire commented on src/main/resources/static/app/service/LoginService.js
> +    .factory('loginService', function ($rootScope, $http) {
fix

2017-05-25 07:54 UTC, GetFire commented on src/main/resources/static/views/user/UserController.js
> +                $location.path('/user/:id', $scope.user.id);
fix

2017-05-25 07:54 UTC, GetFire commented on src/test/java/net/greatstart/controllers/UserRestControllerTest.java
> +        user = new User();
fix

2017-05-25 11:49 UTC, Sheptytskyid commented on src/main/java/net/greatstart/services/UserService.java
> +    //ToDo: Rewrite method for create/delete User
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarqube.com/coding_rules#rule_key=squid%3AS1135)

2017-05-25 11:49 UTC, Sheptytskyid commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

2017-05-25 12:31 UTC, GetFire commented on src/main/java/net/greatstart/controllers/UserRestController.java
> +        User user = userService.getUserByEmail(principal.getName());
fix

2017-05-25 12:31 UTC, GetFire commented on src/main/resources/static/views/user/UserController.js
> +        $scope.user = angular.copy($rootScope.currentUser);
fix

2017-05-25 12:38 UTC, zozich approved these changes
OK

2017-05-25 12:50 UTC, merged